### ISSUE TITLE
Slow Loading Time for Box Manifests

### ISSUE THREAD

**Issue by HopkinsDC** [episphere/biospecimen#548]
Per Stephanie, the BPTL dashboard is taking about 15 seconds to open up a manifest, and this seems slower than usual.

**Comment by StephanieWeinstein** [comment]
thx for posting for me Dominique.
I did ask Norma this morning if this was a problem for her staff and she did not think it was right now.  So priority 2 is good.

**Comment by HopkinsDC** [comment]
Both HealthPartners (6/19) and KPCO (7/17) report low loading times.

**Comment by JoeArmani** [comment]
Related: This is associated with the larger issue of shipping dashboard performance enhancements here: https://github.com/episphere/connect/issues/685
PR to solve this issue is currently in review, located here: https://github.com/episphere/biospecimen/pull/568

**Comment by JoeArmani** [comment]
Hi @HopkinsDC, I think this can be closed. These changes were pushed to production yesterday evening and Box Manifests now load instantly in the shipping dashboard.

**Comment by StephanieWeinstein** [comment]
Hi Joe, This was originally submitted because of slow loading time on the BPTL dashboard, which is still a problem.  Is that part covered in another issue now?  thx.

**Comment by JoeArmani** [comment]
@StephanieWeinstein @HopkinsDC My mistake, sorry. I thought this was related to slow loading for box manifests in the shipping dashboard. We began looking into BPTL today. Thanks.

**Comment by StephanieWeinstein** [comment]
It got a bit mixed up with site issues with shipping dashboards, so completely understandable!

**Comment by wyattks** [comment]
@JoeArmani   Not sure if this instance of slowness is connect to the above report, but Chicago is experiencing slowness when trying to view the  manifest from the Shipping Report.

**Comment by JoeArmani** [comment]
@wyattks Thank you for documenting this.

We have not looked into the 'reports' section yet, so I will mark it for exploration this coming week. I just took a cursory look - some of the same data-handling methods we found in the first shipping dashboard update (and in the current BTPL update) are also used in the reports section.

These can be adapted as we optimize specimen and box handling (the target of the upcoming dev cycle). So, improvement is almost a certainty, I'm just not sure of the time to complete it since I haven't been able to take a deep dive into how this section of the app is constructed yet.

**Comment by Davinkjohnson** [comment]
Kathleen to test the BPTL portion of this in Dev and Stage

**Comment by JoeArmani** [comment]
Note: the recent conversation about slow reports has been turned into a separate issue here: https://github.com/episphere/connect/issues/755

**Comment by JoeArmani** [comment]
This is in production and reports are itemized in a separate issue. The 'slow reports' issue is linked directly above this comment. Closing.
